### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by N6UDP** [metabrainz/logster#3]
Could you all add a license?
Thanks! (FWIW I looked around and some of the other projects under metabrainz that have license files committed are GPL2.. but there are a few other projects missing copying/license info as far as I can tell..)

**Comment by mayhem** [comment]
Do you actually see any use in this code? I've abandoned this project since the core bits are better done by InfluxDB. I'm more inclined to delete this repo to clean things up.

GPL2 would be the license.

**Comment by N6UDP** [comment]
Fair enough -- there is a use case we have for sending the data to collectd/statsd (which could totally be telegraf/influxdb) via logster but the certainly are other ways to do it just happens to fit easily.

**Comment by mayhem** [comment]
Ok, great. This project was far from anything that was ever useful for anyone. :)

**Comment by mayhem** [comment]
Oh ha. I just realized that this is for a completely different project than I recalled. Sorry! I'll get zas to add a license to this. Sorry!

**Comment by N6UDP** [comment]
ok, thanks!
